### ISSUE TITLE
Solvable mine puzzle is not actually solvable.

### ISSUE THREAD

**Issue by vsvjoirwv** [medmunds/puzzles#1]
HI, I have faced the problem mentioned in the header. Here it the screenshot: https://ibb.co/S7YSWJP
Game ID is 49x22:9,12,m5141a7b0615643db1b461184eb1f52ef59a7de6edaea3c5cec7d4f84b8e694d1f4969d86c6b84570d106192ce297d73357451b54e18c4ab254eb79a4ba876ebdf50f4e00a91f90587b22038679ca036af88871ace4351c3e0472db9bc6421098a6343c1560e5e0e2df9a06cf070f21ee81d37791a65a89681d88a27fc97d0ef97c8dd5589b2c24

The solubility is picked: https://ibb.co/3cw3GDP

**Comment by medmunds** [comment]
As a general rule, problems with game logic need to be reported to Simon Tatham's [source puzzle collection](https://www.chiark.greenend.org.uk/~sgtatham/puzzles/) (see the "Feedback" section there). Also, note that this port is no longer actively maintained, so any logic fixes from the past few years won't have made it into here.

However, @vsvjoirwv, in this instance there are several available moves, and I believe the puzzle is solvable.

Consider two possible cases for the cell marked *A* below: either it has a mine, or it doesn't. In either case, all cells marked *H* and *J* will be safe moves to clear.

If *A* does not have a mine:
![minesweeper-possibility 2](https://user-images.githubusercontent.com/639984/207948103-066f7e28-0a9c-448b-a7fd-8dc3ac24ea9d.png)
… then both of cells *B* and *C* must both have mines. In this case, all of *D*, *E* and *F* must be clear, and therefore cell *G* must have a mine. It follows that the cells marked *H* and *J* would all be clear.

Or if *A* **does** have a mine:
![minesweeper-possibility 1](https://user-images.githubusercontent.com/639984/207948119-11efb3bf-7416-4bed-8ef8-90c1a618a8fd.png)
… then both cells *B* and *C* must be clear, and one (but not both) of the cells marked *D* must have a mine. That means exactly one of the cells marked *F* must also have a mine, and the cells marked *H* must all be clear. Also, since one of the *F* cells has a mine, the upper *D* cell must be clear, so the lower *D* cell must have the mine, and the cells marked *J* must be clear.

So whether cell *A* does or does not have a mine, all of cells *H* and *J* must be clear and are valid moves to continue solving the puzzle.
